language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ./xeus-fift-test

before_deploy:
  - fakeroot checkinstall \
    --arch="amd64" \
    --pkgname="xeus-fift" \
    --pkgversion="0.1.0" \
    --pkgrelease="1" \
    --pkglicense="GPL-3" \
    --pkgsource="https://github.com/m-kus/xeus-fift" \
    --maintainer="mz@baking-bad.org" \
    --install=no -y -D -d2 make install

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: xeus-fift_0.1.0-1_amd64.deb
  skip_cleanup: true
  draft: true
  on:
    branch: master
    type: push